import ExcelJS from "npm:exceljs@4.4.0";

// Helper function to parse chemical format "X:YYYkgs"
const parseChemical = (chemStr: string): number => {
  if (!chemStr) return 0;
  const parts = chemStr.split(':');
  if (parts.length === 2) {
    const whole = parseInt(parts[0]) || 0;
    const decimalPart = parts[1].replace('kgs', '').padStart(3, '0');
    return parseFloat(`${whole}.${decimalPart}`);
  }
  return 0;
};

// Helper function to fetch and add image to workbook with timeout
async function addImageToWorkbook(workbook: any, imageUrl: string): Promise<number | null> {
  try {
    if (!imageUrl || imageUrl.trim() === '') return null;
    
    // Fetch with timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout per image
    
    const response = await fetch(imageUrl, { 
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0', // Some servers require user agent
      }
    });
    clearTimeout(timeoutId);
    
    if (!response.ok) {
      console.warn(`⚠️ Failed to fetch image (${response.status}): ${imageUrl}`);
      return null;
    }
    
    const arrayBuffer = await response.arrayBuffer();
    
    // Skip if image is too large (>5MB)
    if (arrayBuffer.byteLength > 5 * 1024 * 1024) {
      console.warn(`⚠️ Image too large (${(arrayBuffer.byteLength / 1024 / 1024).toFixed(2)}MB), skipping: ${imageUrl}`);
      return null;
    }
    
    const buffer = new Uint8Array(arrayBuffer);
    
    // Determine extension from URL or content type
    let extension = 'jpeg';
    if (imageUrl.includes('.png')) extension = 'png';
    else if (imageUrl.includes('.jpg') || imageUrl.includes('.jpeg')) extension = 'jpeg';
    
    const imageId = workbook.addImage({
      buffer: buffer,
      extension: extension,
    });
    
    return imageId;
  } catch (error) {
    if (error.name === 'AbortError') {
      console.warn(`⚠️ Image fetch timeout: ${imageUrl}`);
    } else {
      console.warn(`⚠️ Error adding image ${imageUrl}:`, error.message);
    }
    return null;
  }
}

export async function generateFastExcel(data: any): Promise<Uint8Array> {
  const startTime = Date.now();
  try {
    const { startDate, endDate, dailyData, grandTotals, generatedBy } = data;

    console.log(`🚀 Fast Excel generation with images: ${startDate} to ${endDate}`);
    console.log(`📊 Processing ${dailyData?.length || 0} days of data`);
    
    // Debug: Check if dailyProductionCost is being received
    if (dailyData && dailyData.length > 0) {
      console.log(`🧮 Production Cost Debug:`);
      dailyData.forEach((day, idx) => {
        console.log(`  Day ${idx + 1} (${day.date}): dailyProductionCost = ${day.dailyProductionCost}`);
      });
    }

    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Production Report');

    // Set column widths - 11 columns (removed Production Cost column)
    sheet.columns = [
      { width: 12 },  // Date
      { width: 15 },  // Table
      { width: 10 },  // Shift
      { width: 18 },  // Party Name
      { width: 15 },  // Design No
      { width: 12 },  // Than No
      { width: 12 },  // Qty (M)
      { width: 14 },  // Chemical (kgs)
      { width: 30 },  // Colors
      { width: 15 },  // Created By
      { width: 25 },  // Supporting Pictures
    ];

    let currentRow = 1;

    // Title
    sheet.mergeCells(`A${currentRow}:L${currentRow}`);
    const titleCell = sheet.getCell(`A${currentRow}`);
    titleCell.value = 'PRODUCTION TRACKING REPORT';
    titleCell.font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getRow(currentRow).height = 25;
    currentRow++;

    // Date Range
    sheet.mergeCells(`A${currentRow}:L${currentRow}`);
    const dateRangeCell = sheet.getCell(`A${currentRow}`);
    dateRangeCell.value = `Period: ${startDate} to ${endDate}  |  Generated by: ${generatedBy}`;
    dateRangeCell.font = { size: 11 };
    dateRangeCell.alignment = { horizontal: 'center' };
    currentRow += 2;

    // Collect all unique image URLs
    console.log('📸 Pre-loading all images...');
    const imageLoadStart = Date.now();
    const uniqueImageUrls = new Set<string>();
    
    for (const day of dailyData) {
      if (day.entries) {
        for (const entry of day.entries) {
          if (entry.referencePictures && Array.isArray(entry.referencePictures)) {
            for (const pic of entry.referencePictures) {
              if (pic && pic.trim() !== '') {
                uniqueImageUrls.add(pic);
              }
            }
          }
        }
      }
    }
    
    console.log(`📸 Found ${uniqueImageUrls.size} unique images to load`);
    
    // FIX: Load images in small sequential batches instead of all at once with Promise.all.
    // Promise.all fetches ALL images into RAM simultaneously — with many large images this
    // alone can exceed the Supabase Edge Function memory limit and cause OOM crashes.
    const imageMap = new Map<string, number | null>();
    const IMAGE_BATCH_SIZE = 5; // process 5 images at a time — balances speed vs memory
    const MAX_TOTAL_IMAGES = 30; // hard cap: skip images beyond this to prevent OOM
    if (uniqueImageUrls.size > 0) {
      const urlArray = Array.from(uniqueImageUrls).slice(0, MAX_TOTAL_IMAGES);
      if (uniqueImageUrls.size > MAX_TOTAL_IMAGES) {
        console.warn(`⚠️ Capping images at ${MAX_TOTAL_IMAGES} (found ${uniqueImageUrls.size}) to prevent memory overflow`);
      }
      let successCount = 0;
      for (let i = 0; i < urlArray.length; i += IMAGE_BATCH_SIZE) {
        const batch = urlArray.slice(i, i + IMAGE_BATCH_SIZE);
        const batchResults = await Promise.all(batch.map(async (url) => {
          try {
            const imageId = await addImageToWorkbook(workbook, url);
            return { url, imageId };
          } catch (error) {
            console.warn(`⚠️ Failed to load image ${url}:`, error.message);
            return { url, imageId: null };
          }
        }));
        for (const { url, imageId } of batchResults) {
          imageMap.set(url, imageId);
          if (imageId !== null) successCount++;
        }
        console.log(`  → Image batch ${Math.floor(i / IMAGE_BATCH_SIZE) + 1}: loaded ${batchResults.filter(r => r.imageId !== null).length}/${batch.length}`);
      }
      console.log(`✅ Loaded ${successCount}/${urlArray.length} images in ${((Date.now() - imageLoadStart) / 1000).toFixed(2)}s`);
    }

    // Loop through days
    for (const day of dailyData) {
      // Day Header
      sheet.mergeCells(`A${currentRow}:L${currentRow}`);
      const dayHeader = sheet.getCell(`A${currentRow}`);
      dayHeader.value = `DATE: ${day.date}`;
      dayHeader.font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
      dayHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF70AD47' } };
      dayHeader.alignment = { horizontal: 'left', vertical: 'middle' };
      sheet.getRow(currentRow).height = 20;
      currentRow++;

      // Production entries
      if (day.entries && day.entries.length > 0) {
        // Column headers - REMOVED "Production Cost (Rs/M)" column
        const headerRow = sheet.getRow(currentRow);
        headerRow.values = [
          'Date', 'Table', 'Shift', 'Party Name', 'Design No.', 'Than No.', 
          'Qty (M)', 'Chemical (kgs)', 'Colors', 'Created By', 'Supporting Pictures'
        ];
        headerRow.font = { bold: true };
        headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9E1F2' } };
        headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
        currentRow++;

        // Data rows
        for (const entry of day.entries) {
          const startRowForEntry = currentRow;
          const row = sheet.getRow(currentRow);
          const chemicalKgs = parseChemical(entry.chemical);
          
          // REMOVED production cost from row values - it now shows only in daily summary
          row.values = [
            day.date,
            entry.team.split('+ ').join(', '),
            entry.shift,
            entry.partyName,
            entry.designNo,
            entry.thanNo,
            entry.qtyMeters,
            chemicalKgs.toFixed(3),
            entry.colors,
            entry.createdBy,
            '', // Pictures column (will add images)
          ];

          // Calculate row height based on number of images
          const hasPictures = entry.referencePictures && entry.referencePictures.length > 0;
          if (hasPictures) {
            const numPics = entry.referencePictures.length;
            // Each image takes about 60 pixels height, stack them vertically
            row.height = Math.max(60, numPics * 65);
          } else {
            row.height = 20;
          }

          // Add borders - Updated to 11 columns
          for (let col = 1; col <= 11; col++) {
            row.getCell(col).border = {
              top: { style: 'thin' },
              left: { style: 'thin' },
              bottom: { style: 'thin' },
              right: { style: 'thin' }
            };
          }

          // Add images to the Pictures column (L)
          if (hasPictures) {
            let imageOffset = 0;
            for (let i = 0; i < entry.referencePictures.length; i++) {
              const picUrl = entry.referencePictures[i];
              const imageId = imageMap.get(picUrl);
              
              if (imageId !== null && imageId !== undefined) {
                try {
                  sheet.addImage(imageId, {
                    tl: { col: 10, row: startRowForEntry - 1 + imageOffset }, // Column K (0-indexed = 10)
                    ext: { width: 150, height: 60 }, // Smaller images for faster rendering
                  });
                  imageOffset += 0.95; // Stack images with slight overlap
                } catch (imgError) {
                  console.warn(`⚠️ Failed to add image to cell:`, imgError.message);
                }
              }
            }
          }

          currentRow++;
        }

        // Daily totals
        const dailyTotalRow = sheet.getRow(currentRow);
        dailyTotalRow.values = [
          '', '', '', '', '', 'Daily Total:', 
          day.dailyTotalMeters,
          day.dailyTotalChemical.toFixed(3),
          '', ''
        ];
        dailyTotalRow.font = { bold: true };
        dailyTotalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } };
        currentRow++;
      }

      // Electricity
      if (day.electricityEntries && day.electricityEntries.length > 0) {
        currentRow++;
        
        const elecHeader = sheet.getRow(currentRow);
        elecHeader.values = ['', 'Electricity Consumption', '', '', '', '', '', '', '', '', ''];
        sheet.mergeCells(`B${currentRow}:K${currentRow}`);
        const elecHeaderCell = sheet.getCell(`B${currentRow}`);
        elecHeaderCell.font = { bold: true, size: 11 };
        elecHeaderCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFC000' } };
        currentRow++;

        for (const elec of day.electricityEntries) {
          const elecRow = sheet.getRow(currentRow);
          elecRow.values = [
            '', 
            `Prev: ${elec.previousReading} kWh → Curr: ${elec.currentReading} kWh`,
            '', '', '', '',
            `${elec.consumption.toFixed(2)} kWh`,
            '', 
            `₹${elec.totalCost.toFixed(2)}`,
            ''
          ];
          sheet.mergeCells(`B${currentRow}:E${currentRow}`);
          sheet.mergeCells(`G${currentRow}:H${currentRow}`);
          currentRow++;
        }

        if (day.dailyElectricityCost > 0) {
          const dailyElecRow = sheet.getRow(currentRow);
          dailyElecRow.values = [
            '', '', '', '', '', 'Daily Electricity:',
            `${day.dailyElectricityConsumption.toFixed(2)} kWh`,
            '', 
            `₹${day.dailyElectricityCost.toFixed(2)}`,
            ''
          ];
          dailyElecRow.font = { bold: true };
          dailyElecRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFE699' } };
          currentRow++;
        }
      }
      
      // ✅ Production Cost row - Show AFTER Daily Electricity
      if (day.dailyTotalMeters > 0) {
        const prodCostRow = sheet.getRow(currentRow);
        prodCostRow.values = [
          '', '', '', '', '', 'Production Cost:', 
          '', '', 
          `₹${Number(day.dailyProductionCost).toFixed(2)}/M`,
          ''
        ];
        prodCostRow.font = { bold: true, color: { argb: 'FF0070C0' } };
        prodCostRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE7F3FF' } };
        currentRow++;
      }

      currentRow += 2; // Space between days
    }

    // Grand Totals
    currentRow++;
    sheet.mergeCells(`A${currentRow}:K${currentRow}`);
    const grandTotalHeader = sheet.getCell(`A${currentRow}`);
    grandTotalHeader.value = 'GRAND TOTALS (ENTIRE PERIOD)';
    grandTotalHeader.font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
    grandTotalHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFC00000' } };
    grandTotalHeader.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getRow(currentRow).height = 25;
    currentRow++;

    const grandTotalRows = [
      ['Total Meters:', Number(grandTotals.totalMeters || 0).toFixed(2), 'M'],
      ['Total Chemical:', Number(grandTotals.totalChemical || 0).toFixed(3), 'kgs'],
      ['Total Electricity Consumption:', Number(grandTotals.totalElectricityConsumption || 0).toFixed(2), 'kWh'],
      ['Total Electricity Cost:', `₹${Number(grandTotals.totalElectricityCost || 0).toFixed(2)}`, ''],
      ['Average Production Cost:', `₹${Number(grandTotals.averageProductionCost || 0).toFixed(2)}/M`, `(${grandTotals.numberOfDays || 0} days)`],
    ];

    for (const [label, value, unit] of grandTotalRows) {
      const row = sheet.getRow(currentRow);
      row.values = ['', '', '', label, '', '', value, unit, '', '', '', ''];
      sheet.mergeCells(`D${currentRow}:F${currentRow}`);
      sheet.mergeCells(`G${currentRow}:H${currentRow}`);
      row.getCell('D').font = { bold: true, size: 12 };
      row.getCell('G').font = { bold: true, size: 12, color: { argb: 'FF0070C0' } };
      row.getCell('D').alignment = { horizontal: 'right' };
      row.getCell('G').alignment = { horizontal: 'center' };
      currentRow++;
    }

    // Footer
    currentRow += 2;
    sheet.mergeCells(`A${currentRow}:L${currentRow}`);
    const footer = sheet.getCell(`A${currentRow}`);
    footer.value = `Report generated on ${new Date().toLocaleString()} by ${generatedBy}`;
    footer.font = { italic: true, size: 9, color: { argb: 'FF808080' } };
    footer.alignment = { horizontal: 'center' };

    // Generate buffer
    console.log('📝 Writing Excel workbook to buffer...');
    const bufferStart = Date.now();
    const buffer = await workbook.xlsx.writeBuffer();
    const bufferTime = ((Date.now() - bufferStart) / 1000).toFixed(2);
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`✅ Fast Excel generated (${buffer.byteLength} bytes) in ${elapsed}s (buffer write: ${bufferTime}s)`);
    
    // Ensure we return a proper Uint8Array
    if (!(buffer instanceof ArrayBuffer)) {
      console.log('⚠️ Converting buffer to ArrayBuffer');
    }
    
    return new Uint8Array(buffer);
  } catch (error) {
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
    console.error(`❌ Fast Excel error after ${elapsed}s:`, error);
    console.error('❌ Error details:', {
      message: error.message,
      stack: error.stack,
      name: error.name,
    });
    throw error;
  }
}
